### Checking user creation with an invalid email
GET http://localhost:8000/users   

### Check for Age Validation
POST http://localhost:8000/user
Content-Type: application/json

{
  "name": "Rajike Ekanayake",
  "email": "rajike.ekanayake@example.com",
  "age": 17
}

### Check for Age Validation correct age
POST http://localhost:8000/user
Content-Type: application/json

{
  "name": "Rajike Ekanayake",
  "email": "rajike.ekanayake@example.com",
  "age": 25
}


#  "id": "68515e557f5814161bcffbac"

### Checking user creation with an invalid email
GET http://localhost:8000/users   