version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: my_mongo_db
    restart: always
    ports:
      - "27017:27017" # Exposes MongoDB on localhost:27017
    volumes:
      - ./mongo-data:/data/db # Mounts local ./mongo-data to container's /data/db
    # To enable MongoDB authentication, uncomment the following lines
    # and provide a username and password. This is recommended for any non-trivial setup.
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: myuser
    #   MONGO_INITDB_ROOT_PASSWORD: mypassword

  mongo-express:
    image: mongo-express:latest
    container_name: my_mongo_express
    restart: always
    ports:
      - "8081:8081" # Exposes Mongo Express on localhost:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo # Tells Mongo Express to connect to the 'mongo' service
      ME_CONFIG_MONGODB_PORT: 27017
      # If you enabled MongoDB authentication in the 'mongo' service above,
      # uncomment these lines and use the same credentials.
      # ME_CONFIG_MONGODB_ADMINUSERNAME: myuser
      # ME_CONFIG_MONGODB_ADMINPASSWORD: mypassword
      # ME_CONFIG_MONGODB_ENABLE_ADMIN: "true" # Set to true to allow admin operations via Mongo Express

      # Basic authentication for the Mongo Express UI itself
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongo # Ensures mongo service starts before mongo-express